name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Build Docker images
      run: docker-compose build --build-arg INSTALL_DEV=true

    - name: Start services
      run: docker-compose up -d api redis

    - name: Run tests
      run: docker-compose run --rm test-runner

    - name: Stop services
      run: docker-compose down
